apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-mlflow-image-tensorflow-housing-
spec:
  params:
  - name: model-name
    value: tensorflow-housing
  - name: model-version
    value: "1"
  - name: test-endpoint
    value: "v1/models/tensorflow-housing/versions/1:predict"
  - name: target-namespace
    value: $(context.pipelineRun.namespace)
  - name: target-imagerepo
    value: rhoai-edge
  pipelineRef:
    name: test-mlflow-image
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - secret: 
      secretName: rhoai-edge-build-pull-secret
    name: dockerconfig
  - emptyDir: {}
    name: workspace
  - configMap:
      name: tensorflow-housing-test-data
    name: test-data
